### ISSUE TITLE
[!] Unable to find a specification for `MagicTimer`

### ISSUE THREAD

**Issue by ArjunBhilare** [sadeghgoo/MagicTimer#2]
While using `pod 'MagicTimer'` I'm getting the following error

**[!] Unable to find a specification for `MagicTimer`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.**

**Comment by sadeghgoo** [comment]
Try to update your cocoa pods using the following  command 
`$ sudo gem install cocoapods`
