### ISSUE TITLE
Custom text formatter

### ISSUE THREAD

**Issue by cioraneanu** [sadeghgoo/MagicTimer#4]
Is there any way currently to provide a custom formatter to for the displayed text?

**Comment by sadeghgoo** [comment]
Currently this feature is not available but in the next update we add can add this feature.

Any way you can use MagicTimer(logical heart of MagicTimerView)instead. Then use your custom text formatter. 
MagicTimer properties is same as MagicTimerView but the difference is MagicTimer hasn't view.

**Comment by sadeghgoo** [comment]
New update added:
You can now use custom time formatter. For more information read document.
