### ISSUE TITLE
24 Hours to above issue

### ISSUE THREAD

**Issue by parthhirpara** [sadeghgoo/MagicTimer#6]
when i pass time 24 hour to above then other value(time) pass

when i pass below 24 hours then it work proper

**Comment by sadeghgoo** [comment]
> when i pass time 24 hour to above then other value(time) pass
> 
> 
> 
> when i pass below 24 hours then it work proper
> 
> 
> 
>

**Comment by sadeghgoo** [comment]
> when i pass time 24 hour to above then other value(time) pass
> 
> 
> 
> when i pass below 24 hours then it work proper
> 
> 
> 
> 

Paste your code and tell what's exactly happened.

**Comment by parthhirpara** [comment]
> > when i pass time 24 hour to above then other value(time) pass
> > when i pass below 24 hours then it work proper
> 
> Paste your code and tell what's exactly happened.

// timer
 self.addTimer(data: model)
 
 extension HomeBlogVC : MagicTimerViewDelegate {
    func addTimer(data:ModelPost) {
        let timer = MagicTimerView()
        timer.tag = self.arrTimer.count
        
        timer.isActiveInBackground = false
        let remine = get2DigitDHMS(time: data.remainTime ?? "")
        let total = getDateFrome(day: Double(remine.0)!, hour: Double(remine.1)!, minut: Double(remine.2)!, sec: Double(remine.3)!)
        
        timer.mode = .countDown(fromSeconds: TimeInterval(total))//.stopWatch
        
        timer.delegate = self
        timer.startCounting()
        
        self.arrTimer.append(timer)
    }
    
    func timerElapsedTimeDidChange(timer: MagicTimerView, elapsedTime: TimeInterval) {
        //print(elapsedTime)
        let model = self.arrBlogList[timer.tag]
        if elapsedTime == 0 {
            model.isDisplayPost = "0"
            
//            model
        }
        else {
            model.isDisplayPost = "1"
            
            let totalSec = getFullDHMSFrome(sec: Int(elapsedTime))
            let toalH = (totalSec.0 + totalSec.1)
            let newRemine = "\(toalH):\(totalSec.2):\(totalSec.3)"
            model.remainTime = newRemine
            
        }
        
        
        self.arrBlogList[timer.tag] = model
        
        let cell = self.tableView.cellForRow(at: IndexPath(row: timer.tag, section: 0)) as? DashboardTCell
        if cell != nil {
            cell?.timerData(time: model.remainTime)
        }
    }
}

**Comment by parthhirpara** [comment]
> > when i pass time 24 hour to above then other value(time) pass
> > when i pass below 24 hours then it work proper
> 
> Paste your code and tell what's exactly happened.

Pass this type value
 
        timer.isActiveInBackground = false
        timer.font = UIFont.systemFont(ofSize: 45, weight: .bold)
        timer.mode = .countDown(fromSeconds: 60*24*10)//.stopWatch
        timer.delegate = self

**Comment by parthhirpara** [comment]
> > when i pass time 24 hour to above then other value(time) pass
> > when i pass below 24 hours then it work proper
> 
> Paste your code and tell what's exactly happened.


[ViewController.swift.zip](https://github.com/sadeghgoo/MagicTimer/files/5735083/ViewController.swift.zip)

**Comment by sadeghgoo** [comment]
I will check it soon

**Comment by sadeghgoo** [comment]
> > > when i pass time 24 hour to above then other value(time) pass
> > > when i pass below 24 hours then it work proper
> > 
> > 
> > Paste your code and tell what's exactly happened.
> 
> [ViewController.swift.zip](https://github.com/sadeghgoo/MagicTimer/files/5735083/ViewController.swift.zip)

I will check it soon

**Comment by sadeghgoo** [comment]
> > > when i pass time 24 hour to above then other value(time) pass
> > > when i pass below 24 hours then it work proper
> > 
> > 
> > Paste your code and tell what's exactly happened.
> 
> [ViewController.swift.zip](https://github.com/sadeghgoo/MagicTimer/files/5735083/ViewController.swift.zip)

I checked your code but it does not have any problem. Describe what exactly you do and what happens.
