### ISSUE TITLE
Continue countdown timer after being paused

### ISSUE THREAD

**Issue by dvlpd** [sadeghgoo/MagicTimer#7]
Hello!

Thanks for this library, it has helped me a lot! I have one problem. I have implemented a timer in my app and use 3 button to control this timer: Start, Stop and Pause. The problem is that when user presses Pause the timer pauses, but when the user presses Start, it doesn't continue running from where it was paused, because I don't know how to do that. Here is my code:

`import UIKit
import MagicTimer

class TimerVC: UIViewController {
    
    var currentTaskDefaultTime = 10.0
    

    @IBOutlet weak var timer: MagicTimerView!
    
    @IBOutlet weak var startButton: UIButton!
    
    @IBOutlet weak var pauseButton: UIButton!
    
    @IBOutlet weak var stopButton: UIButton!
    
    @IBAction func pressedStartButton(_ sender: Any) {
        startButton.isHidden = true
        pauseButton.isHidden = false
        stopButton.isHidden = false
        
        timer.mode = .countDown(fromSeconds: currentTaskDefaultTime)
        timer.isActiveInBackground = true
        timer.startCounting()
        
        
        
    }
    
    @IBAction func pressedPauseButton(_ sender: Any) {
        timer.stopCounting()
        startButton.isHidden = false
        completeTaskButton.isHidden = true
    }
    
    @IBAction func pressedStopButton(_ sender: Any) {
        timer.resetToDefault()
        startButton.isHidden = false
        pauseButton.isHidden = true
        stopButton.isHidden = true
    }
    
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        timer.font = UIFont(name: "Comfortaa-Semibold", size: 50)
        
        //hides by default the buttons
        pauseButton.isHidden = true
        stopButton.isHidden = true
    }
    

}
`

Please help me 

Sincerely yours
Nurlan

**Comment by dvlpd** [comment]
I have tried to use **elapsedTime** in the function pressedStartButton to change continue timer from (default time - elapsedTime) if elapsedTime>0, but I get this error:

**'elapsedTime' is inaccessible due to 'internal' protection level**

**Comment by sadeghgoo** [comment]
Hi;
Your sample code is the same as the MagicTimer example please review the example. If the issue exists in the example re-open another issue.

**Comment by sadeghgoo** [comment]
If you want to resume timer just call startCounting() method.
