### ISSUE TITLE
didStateChange Callback is Not Firing on Stop

### ISSUE THREAD

**Issue by hknckr** [sadeghgoo/MagicTimer#9]
Hi,

I am calling callback on viewdidload like that

```
  timer.defaultValue = 10
  timer.isActiveInBackground = true
  timer.mode = .countDown(fromSeconds: 10)
  timer.startCounting()

  timer.didStateChange = { (timer_state) -> Void in
                    print(timer_state)
                }
        
```

The callback works on start and prints state as fired but on stop the callback is not working and never firing.

Am I doing something wrong or it is a kind of a bug ?

thanks

**Comment by sadeghgoo** [comment]
Hi, this callback called when MagicTimerView or MagicTimer calls below methods: 
```swift
startCounting()
--------------
stopCounting()
--------------
resetToDefault()
--------------
reset()
```

**Comment by hknckr** [comment]
Oh I see,  I have used delegate to understand countdown timer stopped, looked at elapsed time value if it is 0 then it means countdown timer is done. I have solved my problem.

But in this function  

private func countDown(fromSeconds: TimeInterval)  (MagicTimer.swift file)

I thought  self.didStateChange?(.stopped)  will  call  callback , but not

```
 guard self.counter.totalCountedValue > 0 else {
                self.executive.suspand()
                self.didStateChange?(.stopped)

                return
            }
```
